version: '3.9'
services:
  wheelwander:
    build:
      context: .
      dockerfile: WheelWander/Dockerfile
    container_name: wheelwander.netcore
    ports:
      - "5000:80"
    depends_on: 
      - wheelwanderdb
    volumes:
      - .:/app  
  
  wheelwanderdb:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: wheelwander.db.sqlserver
    user: root
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=wheelPassword1!
    volumes:
      - .docker/dbdata:/var/opt/mssql/data
