version: '3.9'
services:
  wheelwander:
    build:
      context: .
      dockerfile: WheelWander/Dockerfile
    container_name: ${APP_CONTAINER_NAME}
    ports:
      - "${APP_CONTAINER_PORT}:80"
    depends_on: 
      - wheelwanderdb
    volumes:
      - .:/app  
  
  wheelwanderdb:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: ${DB_CONTAINER_NAME}
    user: root
    ports:
      - "${DB_CONTAINER_PORT}:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_SA_PASSWORD}
    volumes:
      - .docker/dbdata:/var/opt/mssql/data
